### ISSUE TITLE
Add ignore .idea/ to .gitignore

### ISSUE THREAD

**Issue by HaysaRodrigues** [HoraApps/Liz#7]
hey, what do you think we add the .idea/ in .gitignore?

**Comment by dnldsht** [comment]
yeah .idea should be in gitignore! but once you have pushed you cant just gitignore it you have to remove it with `git rm -r --cached .idea/ ` otherwise it will stay there

**Comment by HaysaRodrigues** [comment]
hum, sorry! I saw that you already did it! thanks for telling me. Now I will know next time, haha! 👍
